services:
  - type: web
    name: iptv-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: iptv-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100

databases:
  - name: iptv-db
    databaseName: iptv_production
    user: iptv_user
    plan: starter
